### PR TITLE
Add core files.

### PR DESCRIPTION
**Pull request by mattcollier**
I needed some signature testing software for bedrock-key and determined that there was actually no http-signature specific stuff in `http-signature-crypto`, so I think a more generic name is appropriate.  I checked NPM and `signature-algorithm` is available, but I'm open to other names.

### CODE REVIEW

**Comment by davidlehn** [comment]
Other than some renaming this is code just copied from http-signature-crypto?
signature-algorithm vs signature-algorithms?
This looks similar to the json-web-algorithms package api.

**Comment by mattcollier** [comment]
@davidlehn yes, this is just a copy.

took a peek at json-web-algorithms https://github.com/jhermsmeier/node-json-web-algorithms it is similar, but does not have ed25519 support.

No 's' because I'm saving disk space, I'll go with the consensus opinion on  a new name.

**Comment by davidlehn** [comment]
Yeah, I'm not saying to use that other package, was just pointing it out since I saw it while researching how others handle the tradeoff between disk space and a trailing 's'.

**Comment by mattcollier** [comment]
I found a few non-pluralized modules: 
https://github.com/digitalbazaar/bedrock-key
https://github.com/digitalbazaar/bedrock-identity
https://github.com/digitalbazaar/bedrock-agreement

and the same people also came up with these names:
https://github.com/digitalbazaar/bedrock-messages
https://github.com/digitalbazaar/bedrock-docs
https://github.com/digitalbazaar/bedrock-jobs

**Comment by davidlehn** [comment]
They must be practicing the ancient wisdom that two standards are better than one.

**Comment by dlongley** [comment]
I vote to add an `s` if we keep this generic module. But this module does seem a bit weird to me. How do we determine what gets added (or not) to it over time? Can it bloat to become unwieldy? Should we split the individual algorithms up -- or would that be something to wait to do in the future... but then this module just becomes a shell?

It seems like the future of this module would to provide just the base API for signing/verifying, much like node's crypto lib's `createSigner`/`Signer`/`Verifier` API. The individual algorithms would be their own packages that could be installed. It may be nice to just extend/wrap that existing API ... but that would only work on node.

A monolithic library will become a bigger problem more quickly when we want to use this on the client (which we do want to do). That's another argument to have a simple "plugin" API with individual modules providing the implementations for specific algorithms. Obviously there's additional overhead with more packages, but it seems like the right way to do it.

**Comment by mattcollier** [comment]
@dlongley you are suggesting that we split the algrithms into separate modules?  And would this module load some set of default modules as now?

Can we kick the can on these concerns in the interest of time?  We've added exactly one signature algorithm in the past 3 years.

**Comment by dlongley** [comment]
@mattcollier,

> Can we kick the can on these concerns in the interest of time? We've added exactly one signature algorithm in the past 3 years.

Yes, let's kick the can for now but please leave a TODO to split this module up into a main API with no signatures installed and plugins that people can install to add the signature algorithms they want.

**Pull request merged**
